name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
permissions:
  pull-requests: write
  issues: write

jobs:
  build:
    name: Build TOMB
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: |
          sudo apt-get install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev
          sudo apt-get install libc6-dev libicu-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev librocksdb-dev
          sudo apt-get install librocksdb-dev
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
  Test: 
    name: Test TOMB
    depends-on: build
    steps: 
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/Cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'
          
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
  Comment:
    name: Comment on PR
    needs: [build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-summary.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Comment on PR
       # uses: peter-evans/create-or-update-comment@v1
       # with:
        #  issue-number: ${{ github.event.pull_request.number }}
         # body: |
          #  ## Code Coverage Summary
           # ![Code Coverage Summary](
