name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Get PhantasmaChain
      run: |
        sudo apt-get update
        sudo apt-get -y install git libicu-dev
        git clone https://github.com/phantasma-io/PhantasmaChain.git ../PhantasmaChain
        cd ../PhantasmaChain
        git checkout development
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
